import datetime


class Generator:
    @staticmethod
    def process(code: bytes, template: str,
                loops=1,
                loopdelay=2000,
                initialdelay=5000,
                blink=True,
                blinkdelay=500) -> str:
        sketch = template

        args = {
            "loops": loops,
            "loopdelay": loopdelay,
            "initialdelay": initialdelay,
            "blink": blink,
            "blinkdelay": blinkdelay
        }

        for k, v in args.items():
            sketch = sketch.replace(f"%{k}%", str(v).lower())

        sketch = sketch.replace("%META%", f"Generated by digiduck at {datetime.datetime.now().ctime()}")
        sketch = sketch.replace("%payload_len%", str(len(code)))
        sketch = sketch.replace("%payload%", ", ".join(map(hex, code)))

        return sketch
