import datetime


class Generator:
    @staticmethod
    def process(code: bytes, template: str,
                loops=1,
                loop_delay=2000,
                initial_delay=5000,
                blink=True,
                blink_delay=500) -> str:
        sketch = template

        args = {
            "loops": loops,
            "loop_delay": loop_delay,
            "initial_delay": initial_delay,
            "blink": blink,
            "blink_delay": blink_delay
        }

        for k, v in args.items():
            sketch = sketch.replace(f"%{k}%", str(v).lower())

        sketch = sketch.replace("%META%", f"Generated by digiduck at {datetime.datetime.now().ctime()}")
        sketch = sketch.replace("%payload_len%", str(len(code)))
        sketch = sketch.replace("%payload%", ", ".join(map(hex, code)))

        return sketch
